from datetime import datetime
from sqlalchemy import String,Integer,Float,DateTime,ForeignKey,Text,Boolean
from sqlalchemy.orm import Mapped,mapped_column
from .db import Base
class Org(Base):
 __tablename__='organizations'; id:Mapped[int]=mapped_column(primary_key=True); name:Mapped[str]=mapped_column(String(160)); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class User(Base):
 __tablename__='users'; id:Mapped[int]=mapped_column(primary_key=True); org_id:Mapped[int]=mapped_column(ForeignKey('organizations.id'),index=True); name:Mapped[str]=mapped_column(String(120)); email:Mapped[str]=mapped_column(String(200),unique=True,index=True); password_hash:Mapped[str]=mapped_column(Text); role:Mapped[str]=mapped_column(String(30),default='admin'); active:Mapped[bool]=mapped_column(Boolean,default=True)
class Customer(Base):
 __tablename__='customers'; id:Mapped[int]=mapped_column(primary_key=True); org_id:Mapped[int]=mapped_column(index=True); name:Mapped[str]=mapped_column(String(160)); email:Mapped[str|None]=mapped_column(String(200)); phone:Mapped[str|None]=mapped_column(String(80)); address:Mapped[str]=mapped_column(String(300)); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class Opportunity(Base):
 __tablename__='opportunities'; id:Mapped[int]=mapped_column(primary_key=True); org_id:Mapped[int]=mapped_column(index=True); customer_id:Mapped[int]=mapped_column(ForeignKey('customers.id')); service:Mapped[str]=mapped_column(String(120)); source:Mapped[str]=mapped_column(String(80),default='Manual'); stage:Mapped[str]=mapped_column(String(50),default='New Lead'); value:Mapped[float]=mapped_column(Float,default=0); owner_id:Mapped[int|None]=mapped_column(ForeignKey('users.id')); next_activity:Mapped[str|None]=mapped_column(String(240)); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow); updated_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow,onupdate=datetime.utcnow)
class Job(Base):
 __tablename__='jobs'; id:Mapped[int]=mapped_column(primary_key=True); org_id:Mapped[int]=mapped_column(index=True); opportunity_id:Mapped[int]=mapped_column(ForeignKey('opportunities.id')); status:Mapped[str]=mapped_column(String(50),default='Scheduled'); start_at:Mapped[datetime|None]=mapped_column(DateTime); end_at:Mapped[datetime|None]=mapped_column(DateTime); description:Mapped[str|None]=mapped_column(Text)
class Event(Base):
 __tablename__='events'; id:Mapped[int]=mapped_column(primary_key=True); org_id:Mapped[int]=mapped_column(index=True); opportunity_id:Mapped[int|None]=mapped_column(ForeignKey('opportunities.id')); title:Mapped[str]=mapped_column(String(200)); event_type:Mapped[str]=mapped_column(String(60),default='Appointment'); start_at:Mapped[datetime]=mapped_column(DateTime); end_at:Mapped[datetime|None]=mapped_column(DateTime); notes:Mapped[str|None]=mapped_column(Text)
class Note(Base):
 __tablename__='notes'; id:Mapped[int]=mapped_column(primary_key=True); org_id:Mapped[int]=mapped_column(index=True); opportunity_id:Mapped[int]=mapped_column(ForeignKey('opportunities.id')); author_id:Mapped[int|None]=mapped_column(ForeignKey('users.id')); body:Mapped[str]=mapped_column(Text); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class Document(Base):
 __tablename__='documents'; id:Mapped[int]=mapped_column(primary_key=True); org_id:Mapped[int]=mapped_column(index=True); opportunity_id:Mapped[int]=mapped_column(ForeignKey('opportunities.id')); name:Mapped[str]=mapped_column(String(240)); storage_key:Mapped[str]=mapped_column(String(500)); content_type:Mapped[str|None]=mapped_column(String(160)); size:Mapped[int]=mapped_column(Integer,default=0); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class Estimate(Base):
 __tablename__='estimates'; id:Mapped[int]=mapped_column(primary_key=True); org_id:Mapped[int]=mapped_column(index=True); opportunity_id:Mapped[int]=mapped_column(ForeignKey('opportunities.id')); number:Mapped[str]=mapped_column(String(80)); status:Mapped[str]=mapped_column(String(40),default='Draft'); amount:Mapped[float]=mapped_column(Float,default=0); line_items_json:Mapped[str]=mapped_column(Text,default='[]'); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class Invoice(Base):
 __tablename__='invoices'; id:Mapped[int]=mapped_column(primary_key=True); org_id:Mapped[int]=mapped_column(index=True); opportunity_id:Mapped[int]=mapped_column(ForeignKey('opportunities.id')); number:Mapped[str]=mapped_column(String(80)); status:Mapped[str]=mapped_column(String(40),default='Draft'); amount:Mapped[float]=mapped_column(Float,default=0); due_at:Mapped[datetime|None]=mapped_column(DateTime); external_id:Mapped[str|None]=mapped_column(String(200)); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class Audit(Base):
 __tablename__='audit_log'; id:Mapped[int]=mapped_column(primary_key=True); org_id:Mapped[int]=mapped_column(index=True); user_id:Mapped[int|None]=mapped_column(Integer); action:Mapped[str]=mapped_column(String(100)); entity_type:Mapped[str]=mapped_column(String(80)); entity_id:Mapped[int|None]=mapped_column(Integer); detail:Mapped[str|None]=mapped_column(Text); created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
