import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import{LayoutDashboard,Users,BriefcaseBusiness,CalendarDays,BarChart3,Search,Plus,Phone,Mail,MapPin,Clock,FileText,ChevronRight,HardHat,DollarSign,TrendingUp,MoreHorizontal,X,CheckCircle2,Upload}from'lucide-react';import'./style.css';

type Stage='New Lead'|'Contacted'|'Inspection'|'Estimate Sent'|'Won';
type Lead={id:number,name:string,address:string,phone:string,email:string,source:string,stage:Stage,value:number,service:string,owner:string,next:string,notes:string[]};
const seed:Lead[]=[];
const stages:Stage[]=['New Lead','Contacted','Inspection','Estimate Sent','Won'];
function money(n:number){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n)}
const API='/api';
function api(path:string,opts:any={}){const t=localStorage.getItem('crm_token');return fetch(API+path,{...opts,headers:{...(opts.body instanceof FormData?{}:{'Content-Type':'application/json'}),...(t?{Authorization:'Bearer '+t}:{}),...(opts.headers||{})}}).then(async r=>{if(!r.ok)throw new Error((await r.json().catch(()=>({detail:r.statusText}))).detail||'Request failed');return r.json()})}
function Auth({onReady}:any){const[mode,setMode]=useState('login');const[err,setErr]=useState('');async function submit(e:any){e.preventDefault();setErr('');const f=new FormData(e.currentTarget);try{let data=await api(mode==='setup'?'/bootstrap':'/login',{method:'POST',body:JSON.stringify(mode==='setup'?{company:f.get('company'),name:f.get('name'),email:f.get('email'),password:f.get('password')}:{email:f.get('email'),password:f.get('password')})});localStorage.setItem('crm_token',data.token);onReady()}catch(x:any){setErr(x.message)}}return <div className="auth"><form className="modal authbox" onSubmit={submit}><div className="brand"><div className="brandmark"><HardHat size={20}/></div><div><b>Ridge</b><span>Roofing CRM</span></div></div><h2>{mode==='setup'?'Set up your company':'Welcome back'}</h2><p>{mode==='setup'?'Create the first administrator account.':'Sign in to manage your roofing business.'}</p>{mode==='setup'&&<><label>Company<input name="company" required placeholder="Acme Roofing"/></label><label>Your name<input name="name" required placeholder="Carrie Brown"/></label></>}<label>Email<input name="email" type="email" required/></label><label>Password<input name="password" type="password" minLength={10} required/></label>{err&&<p className="error">{err}</p>}<button className="primary submit">{mode==='setup'?'Create workspace':'Sign in'}</button><button type="button" className="linkbtn" onClick={()=>setMode(mode==='setup'?'login':'setup')}>{mode==='setup'?'Already initialized? Sign in':'First time? Initialize workspace'}</button></form></div>}
function App(){const[page,setPage]=useState('Dashboard');const[leads,setLeads]=useState(seed);const[selected,setSelected]=useState<Lead|null>(null);const[modal,setModal]=useState(false);const[query,setQuery]=useState('');const[ready,setReady]=useState(!!localStorage.getItem('crm_token'));const[loading,setLoading]=useState(true);const load=()=>{if(!localStorage.getItem('crm_token')){setLoading(false);return}api('/leads').then(setLeads).catch(()=>{localStorage.removeItem('crm_token');setReady(false)}).finally(()=>setLoading(false))};useEffect(load,[ready]);if(!ready&&!localStorage.getItem('crm_token'))return <Auth onReady={()=>setReady(true)}/>;if(loading)return <div className="loading">Loading CRM…</div>;
const pipeline=leads.reduce((s,l)=>s+l.value,0),won=leads.filter(l=>l.stage==='Won').reduce((s,l)=>s+l.value,0);
const addLead=async(e:any)=>{e.preventDefault();const f=new FormData(e.currentTarget);const x=await api('/leads',{method:'POST',body:JSON.stringify({name:f.get('name'),address:f.get('address'),phone:f.get('phone'),email:f.get('email'),source:f.get('source'),service:f.get('service'),value:Number(f.get('value'))||0})});setLeads(v=>[x,...v]);setModal(false)};
const move=async(id:number,stage:Stage)=>{const x=await api(`/leads/${id}/stage`,{method:'PATCH',body:JSON.stringify({stage})});setLeads(ls=>ls.map(l=>l.id===id?x:l));};
const nav=[['Dashboard',LayoutDashboard],['Pipeline',TrendingUp],['Customers',Users],['Jobs',BriefcaseBusiness],['Calendar',CalendarDays],['Reports',BarChart3]] as const;
return <div className="app"><aside><div className="brand"><div className="brandmark"><HardHat size={20}/></div><div><b>Ridge</b><span>Roofing CRM</span></div></div><nav>{nav.map(([n,I])=><button className={page===n?'active':''} onClick={()=>setPage(n)}><I size={18}/>{n}{n==='Pipeline'&&<em>{leads.length}</em>}</button>)}</nav><div className="user"><div className="avatar">CB</div><div><b>Carrie Brown</b><span>Administrator</span></div><MoreHorizontal size={18}/></div></aside>
<main><header><div><h1>{page}</h1><p>{page==='Dashboard'?'Here’s what’s happening with your business today.':'Manage your roofing business in one place.'}</p></div><div className="head-actions"><div className="search"><Search size={17}/><input placeholder="Search customers, jobs…" value={query} onChange={e=>setQuery(e.target.value)}/></div><button className="primary" onClick={()=>setModal(true)}><Plus size={17}/>New lead</button></div></header>
{page==='Dashboard'?<Dashboard leads={leads} pipeline={pipeline} won={won} open={setSelected} setPage={setPage}/>:page==='Pipeline'?<Pipeline leads={leads} move={move} open={setSelected}/>:page==='Calendar'?<Calendar leads={leads}/>:page==='Reports'?<Reports leads={leads}/>:<Records title={page} leads={leads} open={setSelected} query={query}/>}</main>
{selected&&<Drawer lead={selected} close={()=>setSelected(null)} move={(s)=>{move(selected.id,s);setSelected({...selected,stage:s})}}/>}
{modal&&<div className="overlay" onMouseDown={()=>setModal(false)}><form className="modal" onSubmit={addLead} onMouseDown={e=>e.stopPropagation()}><div className="modalhead"><div><h2>New lead</h2><p>Add a homeowner or incoming opportunity.</p></div><button type="button" className="icon" onClick={()=>setModal(false)}><X/></button></div><label>Customer name<input required name="name" placeholder="John Smith"/></label><label>Property address<input required name="address" placeholder="123 Main Street"/></label><div className="twocol"><label>Email<input name="email" type="email" placeholder="john@example.com"/></label><label>Phone<input name="phone" placeholder="(555) 555-0123"/></label></div><div className="twocol"><label>Lead source<select name="source"><option>Website</option><option>Google Ads</option><option>Referral</option><option>Manual</option></select></label></div><div className="twocol"><label>Service<select name="service"><option>Roof Replacement</option><option>Roof Repair</option><option>Roof + Gutters</option><option>Inspection</option></select></label><label>Estimated value<input name="value" type="number" placeholder="25000"/></label></div><button className="primary submit"><Plus size={17}/>Create lead</button></form></div>}</div>}
function Dashboard({leads,pipeline,won,open,setPage}:any){return <><section className="stats"><Stat icon={Users} label="Open leads" val={leads.filter((l:Lead)=>l.stage!=='Won').length} sub="2 new this week"/><Stat icon={DollarSign} label="Pipeline value" val={money(pipeline)} sub="Across all opportunities"/><Stat icon={CheckCircle2} label="Won revenue" val={money(won)} sub="This month"/><Stat icon={TrendingUp} label="Close rate" val="32%" sub="↑ 4.2% vs last month"/></section><section className="grid2"><div className="card"><CardHead title="Sales pipeline" action="View pipeline" on={()=>setPage('Pipeline')}/><div className="funnel">{['New Lead','Contacted','Inspection','Estimate Sent','Won'].map((s,i)=>{let a=leads.filter((l:Lead)=>l.stage===s);return <div className="frow"><span>{s}</span><div><i style={{width:`${95-i*12}%`}}></i></div><b>{a.length}</b><em>{money(a.reduce((x:number,l:Lead)=>x+l.value,0))}</em></div>})}</div></div><div className="card"><CardHead title="Upcoming" action="Open calendar" on={()=>setPage('Calendar')}/><div className="events">{leads.slice(0,4).map((l:Lead,i:number)=><button onClick={()=>open(l)}><div className="date"><b>{5+i}</b><span>OCT</span></div><div><b>{l.service}</b><span>{l.name} · {l.address}</span><small><Clock size={13}/>{l.next}</small></div><ChevronRight/></button>)}</div></div></section><section className="card recent"><CardHead title="Recent opportunities" action="View all" on={()=>setPage('Pipeline')}/><Table leads={leads} open={open}/></section></>}
function Stat({icon:I,label,val,sub}:any){return <div className="stat"><div className="stat-top"><span>{label}</span><div><I size={18}/></div></div><strong>{val}</strong><small>{sub}</small></div>}
function CardHead({title,action,on}:any){return <div className="cardhead"><h3>{title}</h3><button onClick={on}>{action}<ChevronRight size={15}/></button></div>}
function Table({leads,open}:any){return <table><thead><tr><th>Customer</th><th>Service</th><th>Status</th><th>Value</th><th>Next activity</th><th></th></tr></thead><tbody>{leads.map((l:Lead)=><tr onClick={()=>open(l)}><td><b>{l.name}</b><span>{l.address}</span></td><td>{l.service}</td><td><span className={'pill p'+l.stage.replaceAll(' ','')}>{l.stage}</span></td><td><b>{money(l.value)}</b></td><td>{l.next}</td><td><ChevronRight size={16}/></td></tr>)}</tbody></table>}
function Pipeline({leads,move,open}:any){return <div className="kanban">{stages.map((s,idx)=><div className="column"><div className="colhead"><b>{s}</b><span>{leads.filter((l:Lead)=>l.stage===s).length}</span><em>{money(leads.filter((l:Lead)=>l.stage===s).reduce((x:number,l:Lead)=>x+l.value,0))}</em></div>{leads.filter((l:Lead)=>l.stage===s).map((l:Lead)=><div className="deal" onClick={()=>open(l)}><div className="deal-top"><span>{l.source}</span><MoreHorizontal size={16}/></div><h3>{l.name}</h3><p><MapPin size={13}/>{l.address}</p><strong>{money(l.value)}</strong><div className="deal-foot"><span>{l.service}</span>{idx<stages.length-1&&<button title="Advance stage" onClick={e=>{e.stopPropagation();move(l.id,stages[idx+1])}}><ChevronRight size={16}/></button>}</div></div>)}</div>)}</div>}
function Calendar({leads}:any){return <div className="card calendar"><div className="calendar-title"><h2>October 2026</h2><div><button>Today</button><button>‹</button><button>›</button></div></div><div className="week">{['Mon 5','Tue 6','Wed 7','Thu 8','Fri 9'].map((d,i)=><div><b>{d}</b>{leads[i]&&<div className="cal-event"><span>{i%2?'FOLLOW UP':'INSPECTION'}</span><b>{leads[i].name}</b><small>{leads[i].next}</small><p>{leads[i].address}</p></div>}</div>)}</div></div>}
function Reports({leads}:any){let sources=['Google Ads','Website','Referral','Repeat'];return <section className="grid2"><div className="card report"><h3>Leads by source</h3>{sources.map(s=>{let n=leads.filter((l:Lead)=>l.source===s).length;return <div className="bar"><span>{s}</span><div><i style={{width:`${Math.max(8,n/leads.length*100)}%`}}/></div><b>{n}</b></div>})}</div><div className="card report"><h3>Pipeline summary</h3>{stages.map(s=><div className="summary"><span>{s}</span><b>{money(leads.filter((l:Lead)=>l.stage===s).reduce((x:number,l:Lead)=>x+l.value,0))}</b></div>)}</div></section>}
function Records({title,leads,open,query}:any){let filtered=leads.filter((l:Lead)=>(l.name+l.address+l.service).toLowerCase().includes(query.toLowerCase()));return <div className="card recent"><div className="cardhead"><h3>{title==='Customers'?'All customers':title==='Jobs'?'Active jobs':'Records'}</h3><span>{filtered.length} records</span></div><Table leads={title==='Jobs'?filtered.filter((l:Lead)=>l.stage==='Won'):filtered} open={open}/></div>}
function Drawer({lead,close,move}:any){return <div className="drawer"><div className="drawerhead"><div><span className={'pill p'+lead.stage.replaceAll(' ','')}>{lead.stage}</span><h2>{lead.name}</h2><p><MapPin size={14}/>{lead.address}</p></div><button className="icon" onClick={close}><X/></button></div><div className="contact"><a><Phone size={16}/>{lead.phone}</a><a><Mail size={16}/>{lead.email}</a></div><div className="value"><span>Opportunity value</span><strong>{money(lead.value)}</strong><small>{lead.service} · {lead.source}</small></div><div className="section"><div className="sectitle"><h3>Stage</h3></div><select value={lead.stage} onChange={e=>move(e.target.value)}>{stages.map(s=><option>{s}</option>)}</select></div><div className="section"><div className="sectitle"><h3>Next activity</h3><button>+ Schedule</button></div><div className="next"><CalendarDays/><div><b>{lead.next}</b><span>Assigned to {lead.owner}</span></div></div></div><div className="section"><div className="sectitle"><h3>Documents</h3><button><Upload size={14}/> Upload</button></div><div className="doc"><FileText/><div><b>Estimate.pdf</b><span>248 KB · 2 days ago</span></div></div></div><div className="section"><div className="sectitle"><h3>Activity & notes</h3><button>+ Note</button></div><div className="timeline">{(lead.notes||[]).map((n:string)=><div><i></i><p>{n}<span>Carrie · recently</span></p></div>)}</div></div></div>}
createRoot(document.getElementById('root')!).render(<App/>);
