-- 0009_files: private storage bucket and register_files (spec §3.4, §4.6).

-- Private bucket, 25 MB per file. No policies on storage.objects: every read and upload goes
-- through a server-signed URL, so the `files` table policies are the only place access is decided.
insert into storage.buckets (id, name, public, file_size_limit)
values ('crm-files', 'crm-files', false, 26214400)
on conflict (id) do update set public = false, file_size_limit = 26214400;

-- ---------------------------------------------------------------------------
-- register_files: records objects that were uploaded to server-generated paths.
-- p: opportunity_id | job_id | customer_id (staff only), [appointment_id],
--    files: [{id, storage_path, file_name, mime_type, size_bytes, [category], [caption]}]
-- Inserts N rows and one `files_uploaded` activity. Safe to call twice: paths already
-- registered are skipped, and nothing is logged when nothing new was inserted.
-- ---------------------------------------------------------------------------
create or replace function public.register_files(p jsonb) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare
  v_job uuid := nullif(p->>'job_id', '')::uuid;
  v_opp uuid := nullif(p->>'opportunity_id', '')::uuid;
  v_customer uuid := nullif(p->>'customer_id', '')::uuid;
  v_appt uuid := nullif(p->>'appointment_id', '')::uuid;
  v_appt_opp uuid;
  v_staff boolean := coalesce(private.is_staff(), false);
  v_files jsonb := coalesce(p->'files', '[]'::jsonb);
  v_prefix text;
  v_ids uuid[];
  v_images int;
  v_count int;
begin
  if private.auth_role() is null then
    raise exception 'not allowed' using errcode = 'insufficient_privilege';
  end if;
  if v_job is not null then
    select opportunity_id into v_opp from public.jobs where id = v_job;
  end if;
  if v_appt is not null then
    select opportunity_id into v_appt_opp from public.appointments where id = v_appt;
    v_opp := coalesce(v_opp, v_appt_opp);
  end if;
  -- Field users reach a deal only through an assignment; a missing deal gets the same answer.
  if not (v_staff or (v_opp is not null and private.field_can_access_opportunity(v_opp))) then
    raise exception 'not allowed' using errcode = 'insufficient_privilege';
  end if;
  if v_appt is not null and v_appt_opp is distinct from v_opp then
    return jsonb_build_object('ok', false, 'code', 'invalid', 'message', 'That appointment belongs to a different deal');
  end if;

  if v_opp is not null then
    select customer_id into v_customer from public.opportunities where id = v_opp;
  elsif not exists (select 1 from public.customers where id = v_customer) then
    v_customer := null;
  end if;
  if v_customer is null then
    return jsonb_build_object('ok', false, 'code', 'not_found', 'message', 'Record not found');
  end if;

  if jsonb_typeof(v_files) <> 'array' or jsonb_array_length(v_files) not between 1 and 50 then
    return jsonb_build_object('ok', false, 'code', 'invalid', 'message', 'Choose between 1 and 50 files');
  end if;

  -- Paths are generated by the server as {customer}/{deal or _}/{file id}.{ext}. Anything else is
  -- refused, so a caller cannot register (and then read) an object that belongs to another record.
  v_prefix := v_customer::text || '/' || coalesce(v_opp::text, '_') || '/';
  if exists (
    select 1 from jsonb_array_elements(v_files) e
     where coalesce((e->>'id') ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$', false) is not true
        or coalesce((e->>'storage_path') ~ ('^' || v_prefix || (e->>'id') || '\.[a-z0-9]{1,5}$'), false) is not true
        or coalesce(length(trim(e->>'file_name')) between 1 and 255, false) is not true
        or coalesce((e->>'mime_type') ~ '^(image/[a-z0-9.+-]+|application/pdf)$', false) is not true
        or coalesce((e->>'size_bytes') ~ '^[0-9]{1,9}$' and (e->>'size_bytes')::bigint between 1 and 26214400, false) is not true
        or (e->>'category' is not null
            and not (e->>'category' = any (enum_range(null::public.file_category)::text[])))
  ) then
    return jsonb_build_object('ok', false, 'code', 'invalid', 'message', 'One of the files is not valid');
  end if;
  if not v_staff and exists (
    select 1 from jsonb_array_elements(v_files) e
     where e->>'category' is not null and e->>'category' not in ('photo', 'measurement_report', 'permit', 'other')
  ) then
    return jsonb_build_object('ok', false, 'code', 'invalid', 'message', 'That category is not available');
  end if;
  if exists (
    select 1 from jsonb_array_elements(v_files) e
     where not exists (select 1 from storage.objects o where o.bucket_id = 'crm-files' and o.name = e->>'storage_path')
  ) then
    return jsonb_build_object('ok', false, 'code', 'not_uploaded', 'message', 'A file did not finish uploading. Try it again.');
  end if;

  -- fill_parent_ids supplies the ancestor ids from the most specific one.
  with inserted as (
    insert into public.files (id, customer_id, opportunity_id, job_id, appointment_id, category, storage_path,
                              file_name, mime_type, size_bytes, caption, uploaded_by)
    select (e->>'id')::uuid, v_customer, v_opp, v_job, v_appt,
           coalesce((e->>'category')::public.file_category,
                    case when e->>'mime_type' like 'image/%' then 'photo' else 'other' end::public.file_category),
           e->>'storage_path', trim(e->>'file_name'), e->>'mime_type', (e->>'size_bytes')::bigint,
           nullif(trim(e->>'caption'), ''), auth.uid()
      from jsonb_array_elements(v_files) e
    on conflict do nothing
    returning id, mime_type
  )
  select coalesce(array_agg(id), '{}'), count(*) filter (where mime_type like 'image/%'), count(*)
    into v_ids, v_images, v_count from inserted;

  if v_count > 0 then
    perform private.log_activity('files_uploaded', v_opp, v_job,
      v_count || case when v_images = v_count then ' photo' else ' file' end
              || case when v_count = 1 then '' else 's' end || ' uploaded',
      jsonb_build_object('count', v_count, 'file_ids', to_jsonb(v_ids), 'appointment_id', v_appt),
      v_customer);
  end if;

  return jsonb_build_object('ok', true, 'count', v_count, 'file_ids', to_jsonb(v_ids));
end $$;

revoke execute on function public.register_files(jsonb) from public, anon, authenticated;
grant execute on function public.register_files(jsonb) to authenticated, service_role;
