-- 0016_estimate_lifecycle: sending, revising, public view / approve / decline, nightly maintenance
-- (spec §7.4, §4.1 events, §4.4).

-- Today in the company timezone.
create or replace function private.business_today() returns date
language sql stable security definer set search_path = '' as $$
  select (now() at time zone coalesce((select timezone from public.company_settings), 'America/New_York'))::date
$$;
revoke execute on function private.business_today() from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- mark_estimate_sent (staff). Called by the send action after the PDF snapshot is stored.
-- One transaction: status, PDF file row, voids the deal's other sent estimates, deal value,
-- stage move with its automation, activity.
-- ---------------------------------------------------------------------------
create or replace function public.mark_estimate_sent(p_estimate_id uuid, p_email text, p_pdf_path text) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare
  e record;
  o record;
  v_email text := nullif(trim(p_email), '');
  v_label text;
  v_target public.opportunity_stage;
  v_missing text[];
  v_file_id uuid;
  v_size bigint;
begin
  if not private.is_staff() then
    raise exception 'not allowed' using errcode = 'insufficient_privilege';
  end if;
  select id, opportunity_id, status, estimate_number, version, total_cents, public_token into e
    from public.estimates where id = p_estimate_id for update;
  if not found then
    return jsonb_build_object('ok', false, 'code', 'not_found', 'message', 'Estimate not found');
  end if;
  v_label := private.estimate_label(e.estimate_number, e.version);
  if e.status in ('sent', 'viewed') then
    return jsonb_build_object('ok', true, 'already', true, 'public_token', e.public_token);
  end if;
  if e.status <> 'draft' then
    return jsonb_build_object('ok', false, 'code', 'not_draft', 'message', 'Only a draft estimate can be sent');
  end if;

  select id, stage, customer_id into o from public.opportunities where id = e.opportunity_id for update;
  if o.stage in ('won', 'lost') then
    return jsonb_build_object('ok', false, 'code', 'deal_closed', 'message', 'This deal is closed');
  end if;
  if e.total_cents <= 0 or not exists (select 1 from public.estimate_line_items where estimate_id = e.id) then
    return jsonb_build_object('ok', false, 'code', 'empty', 'message', 'Add at least one line with a price before sending');
  end if;
  if v_email is null or v_email !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' then
    return jsonb_build_object('ok', false, 'code', 'no_email', 'message', 'The customer needs an email address');
  end if;
  -- The deal moves to Estimate Sent, so it must satisfy that stage's other requirements.
  v_missing := private.check_stage_gate(o.id, 'qualified');
  if array_length(v_missing, 1) > 0 then
    return jsonb_build_object('ok', false, 'code', 'missing_requirements',
      'message', 'Fill in the deal''s owner, work type, address, and a phone or email first', 'missing', to_jsonb(v_missing));
  end if;

  -- The PDF snapshot: the path is generated by the server as {customer}/{deal}/{file id}.pdf.
  if coalesce(p_pdf_path ~ ('^' || o.customer_id || '/' || o.id || '/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.pdf$'), false) is not true then
    return jsonb_build_object('ok', false, 'code', 'invalid', 'message', 'The estimate PDF could not be stored');
  end if;
  select (ob.metadata->>'size')::bigint into v_size from storage.objects ob
   where ob.bucket_id = 'crm-files' and ob.name = p_pdf_path and ob.metadata->>'mimetype' = 'application/pdf';
  if v_size is null then
    return jsonb_build_object('ok', false, 'code', 'invalid', 'message', 'The estimate PDF could not be stored');
  end if;
  v_file_id := substring(p_pdf_path from '([0-9a-f-]{36})\.pdf$')::uuid;
  insert into public.files (id, customer_id, opportunity_id, category, storage_path, file_name, mime_type, size_bytes, uploaded_by)
  values (v_file_id, o.customer_id, o.id, 'estimate', p_pdf_path, 'Estimate ' || v_label || '.pdf', 'application/pdf', v_size, auth.uid())
  on conflict do nothing;

  -- Only one estimate is out with the customer at a time.
  update public.estimates set status = 'void'
   where opportunity_id = o.id and id <> e.id and status in ('sent', 'viewed');
  update public.estimates
     set status = 'sent', sent_at = now(), sent_to_email = v_email, pdf_path = p_pdf_path
   where id = e.id;
  update public.opportunities set estimated_value_cents = e.total_cents where id = o.id;

  perform private.log_activity('estimate_sent', o.id, null, 'Estimate ' || v_label || ' sent to ' || v_email,
    jsonb_build_object('estimate_id', e.id, 'total_cents', e.total_cents));

  -- A first version moves the deal to Estimate Sent, a revision to Negotiation, from any earlier stage.
  v_target := case when e.version > 1 then 'negotiation' else 'estimate_sent' end;
  if array_position(enum_range(null::public.opportunity_stage), o.stage) < array_position(enum_range(null::public.opportunity_stage), v_target) then
    perform private.apply_stage_change(o.id, v_target);
  else
    perform private.complete_auto_task(o.id, 'send_estimate');
    perform private.create_auto_task(o.id, null, 'estimate_followup', 'Follow up on estimate', now() + interval '3 days');
  end if;

  return jsonb_build_object('ok', true, 'public_token', e.public_token);
end $$;

-- ---------------------------------------------------------------------------
-- revise_estimate (staff): a new draft with the same number, version + 1, and a new link.
-- The old version stays as it is until the new one is sent.
-- ---------------------------------------------------------------------------
create or replace function public.revise_estimate(p_estimate_id uuid) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare
  e record;
  v_stage public.opportunity_stage;
  v_existing uuid;
  v_version integer;
  v_id uuid;
begin
  if not private.is_staff() then
    raise exception 'not allowed' using errcode = 'insufficient_privilege';
  end if;
  select * into e from public.estimates where id = p_estimate_id for update;
  if not found then
    return jsonb_build_object('ok', false, 'code', 'not_found', 'message', 'Estimate not found');
  end if;
  if e.status not in ('sent', 'viewed', 'declined', 'expired', 'void') then
    return jsonb_build_object('ok', false, 'code', 'invalid_status',
      'message', case when e.status = 'draft' then 'This estimate is still a draft; edit it directly' else 'An accepted estimate cannot be revised' end);
  end if;
  select stage into v_stage from public.opportunities where id = e.opportunity_id;
  if v_stage in ('won', 'lost') then
    return jsonb_build_object('ok', false, 'code', 'deal_closed', 'message', 'This deal is closed. Reopen it to revise the estimate.');
  end if;

  -- One draft revision at a time: return the one that exists.
  select id into v_existing from public.estimates
   where estimate_number = e.estimate_number and status = 'draft' order by version desc limit 1;
  if v_existing is not null then
    return jsonb_build_object('ok', true, 'estimate_id', v_existing, 'already', true);
  end if;

  select max(version) + 1 into v_version from public.estimates where estimate_number = e.estimate_number;
  insert into public.estimates (opportunity_id, estimate_number, version, title, scope_notes, terms, discount_cents, tax_rate,
                                deposit_percent, valid_until, created_by)
  values (e.opportunity_id, e.estimate_number, v_version, e.title, e.scope_notes, e.terms, e.discount_cents, e.tax_rate,
          e.deposit_percent,
          private.business_today() + coalesce((select estimate_valid_days from public.company_settings), 30), auth.uid())
  returning id into v_id;
  insert into public.estimate_line_items (estimate_id, sort_order, name, description, quantity, unit, unit_price_cents, is_taxable)
  select v_id, sort_order, name, description, quantity, unit, unit_price_cents, is_taxable
    from public.estimate_line_items where estimate_id = e.id order by sort_order;

  perform private.log_activity('estimate_created', e.opportunity_id, null,
    'Estimate ' || private.estimate_label(e.estimate_number, v_version) || ' created as a revision',
    jsonb_build_object('estimate_id', v_id, 'revises', e.id));
  return jsonb_build_object('ok', true, 'estimate_id', v_id);
end $$;

-- ---------------------------------------------------------------------------
-- Public page actions: service role only. The caller holds the estimate's unguessable token.
-- ---------------------------------------------------------------------------

-- First real view of a sent estimate. Anything else is a no-op.
create or replace function public.record_estimate_view(p_token uuid) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare e record;
begin
  if not private.is_service_role() then
    raise exception 'not allowed' using errcode = 'insufficient_privilege';
  end if;
  select id, opportunity_id, status, estimate_number, version into e from public.estimates where public_token = p_token for update;
  if not found or e.status <> 'sent' then
    return jsonb_build_object('ok', true, 'changed', false);
  end if;
  update public.estimates set status = 'viewed', viewed_at = now() where id = e.id;
  perform private.log_activity('estimate_viewed', e.opportunity_id, null,
    'Customer viewed estimate ' || private.estimate_label(e.estimate_number, e.version), jsonb_build_object('estimate_id', e.id));
  return jsonb_build_object('ok', true, 'changed', true);
end $$;

-- Approval: wins the deal (job, invoices) through mark_opportunity_won, then records who approved.
create or replace function public.accept_estimate(p_token uuid, p_name text, p_ip text default null) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare
  e record;
  v_name text := nullif(trim(p_name), '');
  v_ip inet;
  v_won jsonb;
begin
  if not private.is_service_role() then
    raise exception 'not allowed' using errcode = 'insufficient_privilege';
  end if;
  select id, opportunity_id, status, estimate_number, version, valid_until into e
    from public.estimates where public_token = p_token for update;
  if not found then
    return jsonb_build_object('ok', false, 'code', 'not_found', 'message', 'Estimate not found');
  end if;
  if e.status = 'accepted' then
    return jsonb_build_object('ok', true, 'already', true, 'opportunity_id', e.opportunity_id, 'estimate_id', e.id);
  end if;
  if e.status not in ('sent', 'viewed') or (e.valid_until is not null and e.valid_until < private.business_today()) then
    return jsonb_build_object('ok', false, 'code', 'not_available', 'message', 'This estimate is no longer available');
  end if;
  if v_name is null or length(v_name) < 2 or length(v_name) > 200 then
    return jsonb_build_object('ok', false, 'code', 'name_required', 'message', 'Type your full name to approve');
  end if;
  begin
    v_ip := nullif(trim(p_ip), '')::inet;
  exception when others then
    v_ip := null;
  end;

  v_won := public.mark_opportunity_won(e.opportunity_id, e.id);
  if not coalesce((v_won->>'ok')::boolean, false) then
    return v_won;   -- nothing has been written
  end if;

  update public.estimates set accepted_name = v_name, accepted_ip = v_ip where id = e.id;
  perform private.log_activity('estimate_accepted', e.opportunity_id, null,
    'Customer approved estimate ' || private.estimate_label(e.estimate_number, e.version),
    jsonb_build_object('estimate_id', e.id, 'name', v_name));
  return jsonb_build_object('ok', true, 'opportunity_id', e.opportunity_id, 'estimate_id', e.id,
                            'job_id', v_won->'job_id', 'job_number', v_won->'job_number');
end $$;

-- Decline: the deal is not lost automatically; the rep gets a task to call.
create or replace function public.decline_estimate(p_token uuid, p_reason text default null) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare e record;
begin
  if not private.is_service_role() then
    raise exception 'not allowed' using errcode = 'insufficient_privilege';
  end if;
  select id, opportunity_id, status, estimate_number, version into e from public.estimates where public_token = p_token for update;
  if not found then
    return jsonb_build_object('ok', false, 'code', 'not_found', 'message', 'Estimate not found');
  end if;
  if e.status = 'declined' then
    return jsonb_build_object('ok', true, 'already', true, 'opportunity_id', e.opportunity_id, 'estimate_id', e.id);
  end if;
  if e.status not in ('sent', 'viewed') then
    return jsonb_build_object('ok', false, 'code', 'not_available', 'message', 'This estimate is no longer available');
  end if;
  update public.estimates
     set status = 'declined', declined_at = now(), decline_reason = nullif(left(trim(p_reason), 1000), '')
   where id = e.id;
  perform private.log_activity('estimate_declined', e.opportunity_id, null,
    'Customer declined estimate ' || private.estimate_label(e.estimate_number, e.version),
    jsonb_build_object('estimate_id', e.id, 'reason', nullif(left(trim(p_reason), 1000), '')));
  perform private.create_auto_task(e.opportunity_id, null, 'declined_followup', 'Customer declined estimate — call', now() + interval '1 hour');
  return jsonb_build_object('ok', true, 'opportunity_id', e.opportunity_id, 'estimate_id', e.id);
end $$;

-- ---------------------------------------------------------------------------
-- run_nightly_maintenance (service role): expire estimates past their valid-until date, and
-- give every open deal with no next step a task (§4.4). Safe to run more than once a day.
-- ---------------------------------------------------------------------------
create or replace function public.run_nightly_maintenance() returns jsonb
language plpgsql security definer set search_path = '' as $$
declare
  e record;
  o record;
  v_today date := private.business_today();
  v_expired integer := 0;
  v_stale integer := 0;
begin
  if not private.is_service_role() then
    raise exception 'not allowed' using errcode = 'insufficient_privilege';
  end if;

  for e in
    select es.id, es.opportunity_id, es.estimate_number, es.version
      from public.estimates es
     where es.status in ('sent', 'viewed') and es.valid_until is not null and es.valid_until < v_today
     for update of es
  loop
    update public.estimates set status = 'expired' where id = e.id;
    perform private.log_activity('estimate_expired', e.opportunity_id, null,
      'Estimate ' || private.estimate_label(e.estimate_number, e.version) || ' expired', jsonb_build_object('estimate_id', e.id));
    perform private.create_auto_task(e.opportunity_id, null, 'estimate_expired', 'Estimate expired — revise or close', now());
    v_expired := v_expired + 1;
  end loop;

  for o in
    select opp.id from public.opportunities opp
     where opp.stage not in ('won', 'lost')
       and not exists (select 1 from public.tasks t where t.opportunity_id = opp.id and t.status = 'open')
       and not exists (select 1 from public.appointments a
                        where a.opportunity_id = opp.id and a.status = 'scheduled' and a.starts_at > now())
  loop
    perform private.create_auto_task(o.id, null, 'stale_deal', 'No next step set — decide what happens next', now());
    v_stale := v_stale + 1;
  end loop;

  return jsonb_build_object('ok', true, 'expired', v_expired, 'stale', v_stale);
end $$;

revoke execute on function public.mark_estimate_sent(uuid, text, text), public.revise_estimate(uuid),
  public.record_estimate_view(uuid), public.accept_estimate(uuid, text, text), public.decline_estimate(uuid, text),
  public.run_nightly_maintenance() from public, anon, authenticated;
grant execute on function public.mark_estimate_sent(uuid, text, text), public.revise_estimate(uuid) to authenticated, service_role;
grant execute on function public.record_estimate_view(uuid), public.accept_estimate(uuid, text, text),
  public.decline_estimate(uuid, text), public.run_nightly_maintenance() to service_role;
